FROM ubuntu:16.04
MAINTAINER odadph@gmail.com
 
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
 
RUN apt-get install -y openssh-server
RUN mkdir /var/run/sshd

RUN
CMD
COPY
EXPOSE
