---
- name: example syntax debug
  hosts: "{{ myservers }}"
  tasks:
  - name: check file coba.txt dan print hasilnya
    command: cat /home/user/coba.txt
    register: hasil
  - debug:
      var: hasil.stdout

  - debug: 
      msg: >
         play_hosts {{ play_hosts }}

  - debug: msg="ansible_distribution={{ansible_distribution}}"
  
  - name: create variable apt
    command: bash -c "echo \"deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main\" "
    register: repo_line
  - debug: 
      msg: "{{ repo_line.stdout }}"
