## Devel docker

---
- hosts: localhost
  become: true

  tasks:
  - name: install docker
    yum:
       name: docker
       state: present

  - name: start and enabled docker
    service:
          name: docker
          state: started
          enabled: true
